import type { Block } from "@/components/Prose";

export interface BlogPost {
  slug: string;
  title: string;
  category: string;
  date: string;
  author?: string;
  excerpt: string;
  blocks: Block[];
}

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: "maily-partners-with-peldot",
    title: "Maily partners with Peldot",
    category: "Company",
    date: "Jun 1, 2026",
    author: "Max",
    excerpt: "Europe's leading GTM tool partners with Peldot.",
    blocks: [
      { type: "p", text: "How custom buying signals are changing outbound — and how to act on them with Maily." },
      { type: "p", text: "Many outbound teams in 2026 have the same problem." },
      { type: "p", text: "The tools are incredible — Maily especially has made multi-channel outreach something a single rep can run at scale. But the problem is that everyone is reaching out to the same accounts at the same time for the same reasons." },
      { type: "p", text: "“Congrats on the funding round!” Your prospect got that email from 47 other reps this week. “I saw you're hiring...” So did everyone with a ProNet Recruiter seat. “Your company is growing fast...” Yeah. They know." },
      { type: "p", text: "The signals that power most outbound — funding, hiring, and technographics — are getting into the hands of everyone. Every major sales tool pulls from the same handful of data providers. If your trigger for outreach is something that shows up in Prospra, InfoPeak, Ventbase, and ProNet simultaneously, you're not early to the conversation. You may just be in line behind everyone else using the same data." },
      { type: "p", text: "However, the teams winning right now aren't using just better outreach. They're using better signals. Signals that nobody else has. Signals that are specific to how THEY sell, who THEY sell to, and what actually indicates that an account is ready for THEIR product." },
      { type: "p", text: "The solution to that is having your very own custom signals — and the big news is that Maily just partnered with Peldot to add them, working in the background for you, on autopilot. The single biggest unlock most outbound teams haven't discovered yet." },
      { type: "h2", text: "What custom signals actually are" },
      { type: "p", text: "A custom signal is a buying indicator you define based on how your specific business operates." },
      { type: "p", text: "Instead of relying on a pre-packaged list of events — funding, hiring, and technographics — you write a question in plain English that describes what you're actually looking for:" },
      { type: "ul", items: [
        "“Does {account} run ABM campaigns?”",
        "“Is {account} building internal sales tooling instead of buying?”",
        "“Has {account}'s CEO publicly discussed moving upmarket?”",
        "“Does {account} mention MEDDPICC in their job postings?”",
      ] },
      { type: "p", text: "Maily, powered by Peldot's research engine, then monitors every account on your list against these questions. Daily. Across multiple data sources." },
      { type: "p", text: "When the answer changes — when an account starts running ABM, when a CEO mentions an enterprise push in an earnings report, or when a company posts a role for building internal dashboards — you get an update. You can automatically push a lead to the campaign and ask the AI to craft personalized outreach based on the signal context. Not just “something happened.” The what, the why, and the so-what." },
      { type: "p", text: "This is fundamentally different from static signals. Funding rounds happen once. Custom signals are continuously monitored against criteria that only matter to your business. Nobody else is watching for the same things you are, because nobody else has defined the same questions." },
      { type: "p", text: "Custom signals aren't magic. They're research at scale. Peldot's engine pulls from the same sources your best rep would check manually if they had 40 hours to research a single account. The difference is that it does it across hundreds or thousands of accounts, every day, automatically." },
      { type: "h3", text: "If you sell marketing services" },
      { type: "p", text: "Your buyers are CMOs, VPs of Marketing, and Heads of Demand Gen. The standard signals everyone uses — “company raised funding” — don't tell you much. Plenty of funded companies don't need marketing help." },
      { type: "ul", items: [
        "“Does {account} run ABM campaigns?” — If they're already doing account-based marketing, they understand the motion. You're offering to make their ABM better or run it for them.",
        "“Has {account} recently hired a new CMO or VP of Marketing?” — New marketing leaders come in with a mandate to change things. If you're there in week 2, you're part of the conversation.",
        "“Is {account} posting an unusually high number of marketing roles?” — A spike in marketing roles often means they're restructuring how they do marketing.",
        "“Does {account}'s website mention ‘partner program' or ‘channel sales'?” — Companies with partner programs often need co-marketing support.",
      ] },
      { type: "h3", text: "Let's say you sell building equipment or construction tech" },
      { type: "p", text: "Your buyers are project managers, operations directors, and fleet managers. They don't live on ProNet. The standard B2B signals are nearly useless." },
      { type: "ul", items: [
        "“Has {account} pulled a building permit in the last 90 days?” — The ultimate timing signal for construction. A new permit means a new project means equipment needs.",
        "“Is {account} mentioned in any awarded government contracts?” — A company that just won a $50M infrastructure contract is about to scale up fast.",
        "“Does {account} have job postings for heavy equipment operators?” — If they're hiring operators, they need equipment.",
        "“Has {account} announced any new facility construction or expansion?” — Press releases about new facilities signal months of equipment purchasing ahead.",
      ] },
      { type: "h3", text: "Let's say you sell cybersecurity" },
      { type: "p", text: "Your buyers are CISOs, CIOs, and IT security directors. Every company “needs” cybersecurity, but the ones ready to buy right now are those with a triggering event." },
      { type: "ul", items: [
        "“Has {account} been mentioned in a data breach or security incident?” — The 30 days after an incident are when security budgets get emergency approval.",
        "“Is {account} hiring their first CISO or dedicated security role?” — That person will need to build a stack from scratch.",
        "“Does {account} mention SOC 2, ISO 27001, or compliance frameworks in job postings?” — Companies pursuing certifications have deadlines and budgets.",
        "“Has {account} recently expanded into regulated industries (healthcare, finance, government)?” — Moving into a regulated vertical forces an immediate security upgrade.",
      ] },
      { type: "h3", text: "Let's say you sell AI automation" },
      { type: "p", text: "Your buyers are ops leaders, GTM engineers, and increasingly, founders and CEOs who want to do more with fewer people." },
      { type: "ul", items: [
        "“Is {account} hiring for a ‘GTM Engineer' or ‘Revenue Operations' role that mentions AI?” — They'll be evaluating every AI tool on the market in their first 60 days.",
        "“Does {account}'s leadership post about AI adoption or automation on ProNet?” — Public excitement from the top signals internal buy-in.",
        "“Has {account} recently reduced headcount while maintaining or increasing revenue?” — The exact profile that buys automation tools.",
        "“Is {account} using Tablr, Zaplet, or Knit in their current workflow?” — They already have the automation mindset.",
      ] },
      { type: "h2", text: "Why the best teams treat signal-sourced accounts as their core focus" },
      { type: "p", text: "Here's the shift happening right now at the best outbound teams: signals aren't a “nice to have” add-on to their existing list. Signal-sourced accounts ARE the list." },
      { type: "p", text: "A rep has 40 hours a week. They can either spend those hours working a static list of 500 accounts — most of which aren't in-market right now — or they can spend those hours on the 30-40 accounts that had a buying event THIS WEEK, going deep on them. Same rep. Same skills. Same tools. Wildly different results." },
      { type: "ul", items: [
        "Monday morning briefing: the manager reviews the week's signals and assigns the hottest accounts to reps.",
        "Sequences built around the signal, not the persona: a “new sales leader” sequence, a “post-funding” sequence, a “building internal tools” sequence.",
        "Multi-channel execution through Maily: email, ProNet, phone, WhatsApp, SMS — all coordinated around the same buying event.",
        "Signal performance tracking: track reply rates by SIGNAL TYPE, double down on what works, sunset what doesn't.",
      ] },
      { type: "h2", text: "How to run this with Peldot + Maily" },
      { type: "p", text: "The actual setup takes less than 15 minutes." },
      { type: "ul", items: [
        "Start with your signals. Think about what actually indicates a company is ready for what you sell — the weird, niche, specific things that only matter for your business.",
        "Build signal-specific sequences. Don't use one sequence for every signal. The reason for reaching out IS the personalization.",
        "Review weekly. Adjust monthly. Add new signals, retire the ones that don't convert. The system gets smarter because you get smarter about what to watch for.",
      ] },
      { type: "p", text: "The teams that will dominate outbound in the next year aren't the ones with the best email copy or the most sophisticated sequences. They're the ones with the best information." },
      { type: "p", text: "Custom signals give you information nobody else has. Maily lets you act on it faster than anyone else can. That's the edge — and Maily + Peldot is making it happen." },
    ],
  },
  {
    slug: "best-sales-intelligence-platforms",
    title: "Best 11 Sales Intelligence Platforms (2026)",
    category: "Guide",
    date: "Jun 14, 2026",
    excerpt: "A breakdown of the top sales intelligence platforms — ranked by what actually helps you sell.",
    blocks: [
      { type: "p", text: "Most sales intelligence comparisons are vendor-written with self-serving rankings. This guide distinguishes between two categories: intent data (anonymous behavior tracking) and buying signals (verifiable public events). Sales intelligence differs from contact data — intelligence indicates where to focus; contact data reveals who to reach." },
      { type: "h2", text: "The two categories" },
      { type: "p", text: "Intent data platforms monitor IP addresses visiting websites and assign topic-level scores. Even Sensora — a category founder — rebranded away from “intent data,” with Dana Whitfield writing: “Intent data promised to reveal which buyers were ready to buy, but in reality, it mostly told us who was digitally loafing.”" },
      { type: "p", text: "Buying signal platforms track real events (regulatory filings, earnings calls, job postings) with verifiable sources and direct quotes." },
      { type: "h2", text: "The 11 platforms" },
      { type: "ul", items: [
        "Peldot — Custom signals with verified sources",
        "Sensora — Enterprise account-based marketing",
        "Bordata — Cooperative intent data network",
        "InfoPeak — Large-scale contact data plus account-level intent",
        "Tablr — Custom signal workflows via data enrichment",
        "Prospra — Budget option for data and basic engagement",
        "Veridex — European phone-verified mobile data",
        "Accountly — ABM plus programmatic advertising",
        "Conversa — Conversation intelligence",
        "Hearthly — Community-led and product-led signals",
        "Dialform — Quick contact lookups",
      ] },
      { type: "h2", text: "How to choose" },
      { type: "p", text: "Choose intent data for enterprise ABM with $50K+ budgets. Choose buying signals for outbound teams needing specific, verifiable reasons to contact accounts. Choose community signals for PLG companies with active developer communities. Most teams pair a signal platform with a contact data provider to solve complementary problems." },
    ],
  },
  {
    slug: "what-is-a-sales-signal",
    title: "What is a Sales Signal?",
    category: "Education",
    date: "Jun 9, 2025",
    excerpt: "The definition of a buying signal — and why custom, verifiable signals beat generic intent data.",
    blocks: [
      { type: "p", text: "A buying signal is a real, verifiable event that indicates a company is likely ready to purchase a product or service." },
      { type: "p", text: "Not a vague score. Not an anonymous website visit. An actual thing that happened — a press release, a job posting, an earnings call statement, a regulatory filing — that tells a salesperson “this company has a reason to buy, right now.”" },
      { type: "p", text: "The concept is simple. The execution is where most teams get it wrong." },
      { type: "h2", text: "Buying signals vs intent data" },
      { type: "p", text: "These terms get used interchangeably, but they describe very different things." },
      { type: "p", text: "Intent data tracks anonymous behavior — usually IP addresses visiting web pages across a publisher network — and assigns a score. You don't see the source. You can't verify it. You can't reference it on a sales call. It's a black box that tells you an account is “surging” for a topic, without telling you why." },
      { type: "p", text: "Buying signals are specific, observable events tied to a real source. “The CEO announced a company-wide AI deployment on the Q1 earnings call” is a buying signal. “This account is surging for artificial intelligence” is intent data. One gives your rep something to say. The other gives them a number." },
      { type: "h2", text: "Types of buying signals" },
      { type: "h3", text: "1. Leadership and organizational changes" },
      { type: "p", text: "A new CIO, CTO, or VP of Sales often signals a strategic shift. New leaders bring new priorities, new budgets, and new vendor evaluations." },
      { type: "h3", text: "2. Hiring patterns" },
      { type: "p", text: "Job postings reveal what a company is building next — before they announce it publicly. If a manufacturing company posts 6 automation engineering roles in 3 weeks, all reporting to a new VP of Digital, that's a stronger signal than any intent score." },
      { type: "h3", text: "3. Financial events and disclosures" },
      { type: "p", text: "Earnings calls, regulatory filings (10-K, 10-Q, Form D), and press releases contain direct statements from leadership about strategy, budget allocation, and priorities. A CFO disclosing a 40% increase in R&D spend focused on AI is a buying signal you can quote verbatim on a cold call." },
      { type: "h3", text: "4. Product and technology announcements" },
      { type: "p", text: "When a company launches a new product, adopts a new platform, or announces a technology overhaul, they're telling you exactly what they're investing in." },
      { type: "h3", text: "5. Regulatory and compliance changes" },
      { type: "p", text: "A company pursuing SOC 2 certification, responding to new industry regulations, or disclosing compliance changes in public filings is often in the market for tools that support those initiatives." },
      { type: "h2", text: "Generic signals vs custom signals" },
      { type: "p", text: "Most signal tools offer the same pre-built alerts: funding rounds, leadership hires, and technographic changes. These are real signals — but if every sales team gets them from the same vendor, they're not a competitive advantage." },
      { type: "p", text: "The shift happening in 2026 is toward custom signals — questions specific to your exact sales motion, written in your own words. Instead of selecting “Leadership Changes” from a dropdown and getting the same alert as 4,000 other reps, you write: “Did this company's CEO publicly mandate replacing manual processes with automation?” Nobody else is tracking it." },
      { type: "h2", text: "Signal stacking: why one signal isn't enough" },
      { type: "p", text: "A single signal rarely closes a deal. An account with one signal — say, a new CTO hire — is interesting. An account with three signals simultaneously — new CTO, 6 automation roles posted, and a press release about modernizing infrastructure — is urgent. This “Why Now” analysis produces outreach that sounds like you've been tracking the company for weeks. Because you have." },
      { type: "h2", text: "How to use buying signals in outbound sales" },
      { type: "h3", text: "Prioritization" },
      { type: "p", text: "Instead of ranking accounts by firmographics, you rank by signal activity. The account with 3 active signals and a new CTO is the one to call today — even if it's not the biggest company on your list." },
      { type: "h3", text: "Timing" },
      { type: "p", text: "Most outbound fails because of timing, not messaging. Buying signals tell you when something changed — so your outreach arrives at the moment the account is actively thinking about the problem you solve." },
      { type: "h3", text: "Personalization" },
      { type: "p", text: "“We help companies like yours improve efficiency” is noise. “I saw your CEO committed to AI adoption across 180,000 employees at the Q1 earnings call — are you evaluating tools for that?” is a conversation." },
      { type: "h2", text: "Finding buying signals at scale" },
      { type: "p", text: "Tracking buying signals manually works for your top 10 accounts. It doesn't work for 500. Peldot is the platform we built because we were frustrated with both manual research and intent data. You write up to 35 signals in plain English, connect your CRM, and Peldot scans thousands of public sources daily — regulatory filings, job postings, earnings calls, press releases, company websites, and news feeds — to find matches. Every result includes the original source, relevant quotes, and a “Why Now” summary. Setup takes about 15 minutes." },
    ],
  },
  {
    slug: "peldot-vs-sensora",
    title: "Peldot vs Sensora",
    category: "Comparison",
    date: "Jun 15, 2026",
    excerpt: "How custom buying signals with verifiable sources compare to traditional intent data.",
    blocks: [
      { type: "h2", text: "The core difference" },
      { type: "p", text: "Peldot and Sensora operate on fundamentally different models. Sensora monitors anonymous IP visits across publisher networks and assigns topic-level intent scores. Peldot instead lets teams write custom buying signals in plain English and monitors real public events — regulatory filings, earnings calls, job postings, press releases — with verifiable sources attached." },
      { type: "table", head: ["Dimension", "Sensora", "Peldot"], rows: [
        ["What it tracks", "Anonymous IP visits to publisher network", "Real public events (regulatory filings, earnings calls, job postings, press releases)"],
        ["Signal type", "Pre-built topic library (“Cloud Security”)", "Custom signals written in plain English"],
        ["Source verification", "No — black-box score", "Yes — linked source with direct quotes"],
        ["Exclusivity", "Same data sold to every customer", "No other team has your signals"],
        ["Account discovery", "Scores existing accounts", "Discovers net-new accounts matching ICP"],
        ["Setup time", "3 to 6 months typical", "About 15 minutes"],
        ["Contract", "Annual, $50K to $100K+/yr", "Month-to-month from $200/mo"],
        ["Revenue validation", "No", "Signals tested against closed-won deals"],
      ] },
      { type: "h2", text: "How each works" },
      { type: "p", text: "Sensora uses reverse IP lookup to identify companies visiting publisher network sites. When multiple employees from one company visit content about a topic, Sensora marks that account as in-market and assigns an intent score. The critical limitation: identical data gets sold to all customers, eliminating competitive advantage." },
      { type: "p", text: "Peldot teams define specific buying indicators as questions — “Did leadership publicly commit to replacing manual processes with automation?” or “Is this company hiring for roles that only exist if they're deploying our category?” Peldot scans thousands of daily public sources and returns results with original sources and direct quotes." },
      { type: "h2", text: "Key differences" },
      { type: "ul", items: [
        "Customization vs. pre-built: Sensora offers broad categories used by thousands. Peldot enables questions unique to your sales motion.",
        "Transparency vs. black-box: Sensora provides scores without sourcing. Peldot delivers linked sources with quotes your team can verify before outreach.",
        "Multiple signals vs. single score: Sensora produces one account score. Peldot stacks multiple signals into a cohesive narrative.",
        "Discovery vs. scoring: Sensora scores known accounts. Peldot identifies entirely new accounts matching your ICP.",
        "Implementation speed: Sensora requires 6-month implementations. Peldot launches in about 15 minutes.",
        "Cost: Sensora contracts run $40K–$120K+ annually. Peldot is month-to-month from $200/month with unlimited users and no per-seat fees.",
      ] },
      { type: "h2", text: "When each fits best" },
      { type: "p", text: "Sensora is a mature advertising platform for targeted account-based marketing — better for large enterprises (5,000+ employees) needing integration with broader marketing automation infrastructure." },
      { type: "p", text: "Peldot fits outbound sales teams needing verifiable conversation starters, teams frustrated with vague intent signals, mid-market and enterprise sellers using consultative approaches, organizations needing discovery of unknown accounts, and teams wanting rapid implementation without long-term financial commitments." },
      { type: "quote", text: "You close one deal and it's paid for itself. If you try to track this on your own, you're going to miss stuff." },
    ],
  },
];

export function getPost(slug: string) {
  return BLOG_POSTS.find((p) => p.slug === slug);
}
